### ISSUE TITLE
Suggestion: List offline players with perm subtype

### ISSUE THREAD

**Issue by ElTodoFull** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#5]
Sometimes, you'd like to list players who have certain permission, but aren't conneted at the moment.
That's what my suggestion is. World and Nearby is understandable for it to not work, but perm plugins save permissions of players in an accessible way that may allow to list offline players with certain permission.

Thank you in advance.

**Comment by Tanguygab** [comment]
That's part of why I actually added the permission subtype, unfortunately, I quickly realized that it wasn't possible due to how permissions plugin work. They only load online players' permissions, they do load offline players' permissions but only when the plugin needs it (or at least that's how LuckPerms works from what I've understood), so I can't really do it in my expansion, or at least not in a very optimized way.

**Comment by haroldrc** [comment]
i need this
